MVCDemo/Models/Cab.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCDemo.Models
{
    public class Cab
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime ManufacturedDate { get; set; }

        //has a
        public CabType CabType { get; set; }

        public int? CabTypeId { get; set; }
    }
}

MVCDemo/Models/CabType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCDemo.Models
{
    public class CabType
    {

        public int Id { get; set; }

        public string Name { get; set; }
    }
}

MVCDemo/Controllers/CabController.cs
using MVCDemo.Models;
using MVCDemo.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDemo.Controllers
{
    public class CabController : Controller
    {

        private Context context;

        public CabController()
        {
            context = new Context();
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }
        // GET: Cab
        public ActionResult Index()
        {
            return View();
        }
        [Route("Cab/ByType/{Type}")]
         public ActionResult ByType(int type)
        {
            return Content("type " + type);
        }
        public ActionResult BasicDetails()
        {

             var cab = new Cab() { Id = 101, Name = "Tesla" };

            var pass = new Passenger() { Id = 1 };
            return View(cab);

            //return Content("hello");

            //  return HttpNotFound();

            //  return new EmptyResult();

         //   return RedirectToAction("PassengerDetails", "Passenger");
        }

        public List<Passenger> GetPassengers()
        {
            return new List<Passenger>
            {
                new Passenger{Id=1,Name="aditya",Balance=3000},
                new Passenger{Id=2,Name="joshiba",Balance=5000},
                new Passenger{Id=3,Name="saumya",Balance=500},
                new Passenger{Id=4,Name="seema",Balance=400},

            };
        }

       
        public ActionResult CabHistory()
        {
            var cab = new Cab() { Id = 3, Name = "alto", ManufacturedDate = new DateTime(2010, 01, 04) };

            var passlist = GetPassengers();

            var cabpassvm = new CabPassengerViewModel
            {
                Cab = cab,
                Passengers = passlist
            };
            return View(cabpassvm);
        }

        public List<Cab> GetCabs()
        {
            return  new List<Cab>()
            {
                new Cab{Id=1,Name="nissan",ManufacturedDate=new DateTime(2000,01,03)},
                new Cab{Id=2,Name="verna"},
                new Cab{Id=3,Name="lambo"},
                new Cab{Id=4,Name="Audi"},
                new Cab{Id=5,Name="BMW"},

            };
        }



        public ActionResult Details(int id)
        {
            var cabl = context.Cabs;

            var cab = cabl.Include(x=>x.CabType).SingleOrDefault(x => x.Id == id);

            if (cab == null)
                return HttpNotFound();

            return View(cab);
        }
        public ActionResult PrintCabDetails()
        {
            //var cabs = new List<Cab>()
            //{
            //    new Cab{Id=1,Name="nissan",ManufacturedDate=new DateTime(2000,01,03)},
            //    new Cab{Id=2,Name="verna"},
            //    new Cab{Id=3,Name="lambo"},
            //    new Cab{Id=4,Name="Audi"},
            //    new Cab{Id=5,Name="BMW"},

            //};

            var cabs = context.Cabs;

            return View(cabs);
        }

        public ActionResult Sample()
        {

            //ViewBag.CabName = "i20";
            //ViewBag.Driver = "shaswat";

            //ViewData["Title"] = "cab details";

            //TempData["sample"] = "sample data";

            return View();
        }
    }
}

MVCDemo/Views/Cab/BasicDetails.cshtml
@model  MVCDemo.Models.Cab
@{
    ViewBag.Title = "BasicDetails";
}

<h2>BasicDetails</h2>
<p>cab details will be printed here</p>

<h2>@ViewBag.CabName</h2>

<h2>@ViewData["Title"]</h2>
<h2>@TempData["sample"]</h2>

<h2>@Model.Id</h2>
<h2>@Model.Name</h2>

MVCDemo/Views/Cab/CabHistory.cshtml
@model MVCDemo.ViewModel.CabPassengerViewModel
@{
    ViewBag.Title = "CabHistory";
}

<h2>CabHistory</h2>

<h1>@Model.Cab.Name</h1>


@if(Model.Passengers.Count==0){
<p>no one has rented this car </p>
}

<ul>

    @foreach(var passenger in Model.Passengers)
    {
    <h1> Name:<li>@passenger.Name</li></h1>
    <h1>Balance:    <li>@passenger.Balance</li></h1>
    }

    ===============================================
</ul>

MVCDemo/Views/Cab/Details.cshtml
@model MVCDemo.Models.Cab
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<h1>@Model.Id</h1>
<h1>@Model.Name</h1>
<h1>@Model.ManufacturedDate</h1>
<h1>@Model.CabType.Name</h1>

MVCDemo/Views/Cab/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MVCDemo/Views/Cab/PrintCabDetails.cshtml
@model IEnumerable<MVCDemo.Models.Cab>
@{
    ViewBag.Title = "PrintCabDetails";
}

<h2>List of Cabs</h2>

@foreach (var cab in Model)
{
    <li> 
  @Html.ActionLink(cab.Name,"Details","Cab",new { id=cab.Id},null)
 </li>

}

MVCDemo/Views/Cab/Sample.cshtml
@{
    ViewBag.Title = "Sample";
}

<h2>Sample</h2>

<h2>@ViewBag.CabName</h2>
<h2>@ViewBag.Driver</h2>

<h2>@ViewData["Title"]</h2>
<h2>@TempData["sample"]</h2>

@{ 
    int a = 10;
    int b = 20;
    int c = a + b;

    <div>@c</div>
}