MVCDemo/Models/Passenger.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCDemo.Models
{
    public class Passenger
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public double Balance { get; set; }

     

        public AccountType AccountType { get; set; }

        public byte? AccountTypeId { get; set; }
    }
}

MVCDemo/Controllers/PassengerController.cs
using MVCDemo.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDemo.Controllers
{
    public class PassengerController : Controller
    {
        public Context _context;

        public PassengerController()
        {
            _context = new Context();
        }


        protected override void Dispose(bool disposing)
        {

            _context.Dispose();
        }
        // GET: Passenger
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PassengerPrint()
        {
            //eager loading
            var passlist = _context.Passengers.Include(x=>x.AccountType);

            //lazy loading
           // var passlist = _context.Passengers;
            return View(passlist);
        }

        public ActionResult Details(int id)
        {
            //lazy loading 
            var passengerlist = _context.Passengers;

            //eager loading
           var pass = passengerlist.Include(x=>x.AccountType).SingleOrDefault(x => x.Id == id);

           // var pass = passengerlist.SingleOrDefault(x => x.Id == id);
            if(pass == null)
            {
                return HttpNotFound();
            }
            return View(pass);


        }

        public List<Passenger> GetPassengers()
        {
            return new List<Passenger>
            {
                new Passenger{Id=1,Name="aditya",Balance=3000},
                new Passenger{Id=2,Name="joshiba",Balance=5000},
                new Passenger{Id=3,Name="saumya",Balance=500},
                new Passenger{Id=4,Name="seema",Balance=400},

            };
        }
        public ActionResult PassengerDetails()
        {

           var passenger = new Passenger() { Id = 1, Name = "aditya", Balance = 3000 };

          //  var cab = new Cab() { Name = "nissan" };
            
            return View(passenger);


        }
    }
}

MVCDemo/Views/Passenger/Details.cshtml
@model MVCDemo.Models.Passenger
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<h1>@Model.Id</h1>
    
<h1>@Model.Name</h1>

<h1>@Model.Balance</h1>

<h1>Offer Rate :@Model.AccountType.OfferRate</h1>

MVCDemo/Views/Passenger/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MVCDemo/Views/Passenger/PassengerDetails.cshtml
@model MVCDemo.Models.Passenger
@{
    ViewBag.Title = "PassengerDetails";
}

<h2>PassengerDetails</h2>

<h2>@Model.Id</h2>
<h2>@Model.Name</h2>
<h2>@Model.Balance</h2>

MVCDemo/Views/Passenger/PassengerPrint.cshtml
@model IEnumerable<MVCDemo.Models.Passenger>
@{
    ViewBag.Title = "PassengerPrint";
}

<h2>PassengerPrint</h2>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Balance
            </th>

            <th>
                OfferRate
            </th>
        </tr>
    </thead>

    <tbody>

@foreach(var item in Model)
{
    <tr>
        <td>
            @Html.ActionLink(item.Name,"Details","Passenger",new { id=item.Id},null)
        </td>

        <td>
            @Html.DisplayFor(m=>item.Balance)
        </td>

        <td>
            @Html.DisplayFor(m=>item.AccountType.Name)
        </td>
    </tr>
}
</tbody>
</table>